name: "Deploy Converter"
on: 
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to code
        uses: actions/checkout@v3
      - name: "deploy"
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

          command: |
            cd ${{ secrets.PG_FOLDER }};
            git checkout main;
            git pull;
            docker compose down;
            docker compose up --build -d;
            
